name: interval_tree
version: 0.2.0+1
description: >-
  A non-overlapping interval tree with support for calculating unions,
  intersections, and differences between individual intervals and entire
  trees.
homepage: https://github.com/jpnurmi/interval_tree
repository: https://github.com/jpnurmi/interval_tree
issue_tracker: https://github.com/jpnurmi/interval_tree/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  meta: ^1.1.8
  quiver: ^2.1.3
dev_dependencies:
  test: ^1.14.2
  test_coverage: ^0.4.1
